# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Random Walks
author: Stratis Markou

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/stratisMarkou/random-walks  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  #branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-HP14V4DGEF
  favicon: _static/img/dicefav.png

sphinx:
  config:
    bibtex_reference_style: author_year
    rediraffe_branch: 'master'
    rediraffe_redirects:
      content/misc/rff/rff.ipynb: book/papers/rff/rff.ipynb
      content/misc/svgd/svgd.ipynb: book/papers/svgd/svgd.ipynb
      content/misc/score-matching/score-matching.md: book/papers/score-matching/score-matching.md

  extra_extensions:
    - sphinx_proof
    - sphinxext.rediraffe